
cmd_help() {
  printf "\n${B}${CY}  relay${R} ${D}%s — multi-account switcher for Claude Code${R}\n\n" "$(_read_version)"

  printf "  ${B}Inside Claude Code (prefix with !)${R}\n"
  printf "  %-42s %s\n" "  !relay"           "account menu + 5hr usage"
  printf "  %-42s %s\n" "  !relay 2"         "switch to account #2 (by index shown in the menu)"
  printf "  %-42s %s\n" "  !relay work"      "switch to account named 'work'"
  printf "  %-42s %s\n" "  !relay status"    "detailed usage for current account"
  echo ""

  printf "  ${B}Account management${R}\n"
  printf "  %-42s %s\n" "  relay add <name>"         "add account via browser login (opens claude /login)"
  printf "  %-42s %s\n" "  relay add-force <name>"   "wipe stored creds/meta first, then force re-login"
  printf "  %-42s %s\n" "  relay refresh <name>"     "re-login to refresh an expired/expiring token"
  printf "  %-42s %s\n" "  relay refresh-all"        "silent OAuth refresh for every stored account"
  printf "  %-42s %s\n" "  relay save <name>"        "save whatever is currently logged in as <name>"
  printf "  %-42s %s\n" "  relay rename <old> <new>" "rename an account (updates order + current pointer)"
  printf "  %-42s %s\n" "  relay remove <name>"      "delete an account (alias: rm, del)"
  printf "  %-42s %s\n" "  relay reorder"            "interactively change account display/switch order"
  printf "  %-42s %s\n" "  relay switch <name|#>"    "switch account by name or index (alias: sw, use)"
  printf "  %-42s %s\n" "  relay <name>"             "bare name/index also switches (shortcut for switch)"
  printf "  %-42s %s\n" "  relay continue [name]"    "optionally switch, then exec 'claude --continue' (alias: cont, c)"
  echo ""

  printf "  ${B}Listing & status${R}\n"
  printf "  %-42s %s\n" "  relay list"               "full account list with weekly usage (alias: ls)"
  printf "  %-42s %s\n" "    -f, --follow"           "live-refresh mode, redraws every 30s (Ctrl+C to exit)"
  printf "  %-42s %s\n" "    --no-usage"             "list without querying the usage API (fast, offline)"
  printf "  %-42s %s\n" "  relay status"             "detailed usage for the current account (alias: st)"
  printf "  %-42s %s\n" "    -f"                     "live-refresh current account status"
  printf "  %-42s %s\n" "  relay sessions"           "show all local Claude sessions (alias: sess)"
  echo ""

  printf "  ${B}One-off runs${R}\n"
  printf "  %-42s %s\n" "  relay run <name>"           "one-off session on an account or provider, then exec claude"
  printf "  %-42s %s\n" "  relay run <name> -- <args>" "forward extra args to claude itself, e.g. -- --resume"
  printf "  %-42s %s\n" "  relay run <name> --codex"   "force Codex CLI for this run, regardless of the provider's stored agent"
  printf "  %-42s %s\n" "  relay run <name> --claude"  "force Claude Code for this run (override a provider's stored --codex)"
  printf "  %-42s %s\n" "  relay run -c|--resume"      "replay last account/provider used by 'relay run' in this dir"
  echo ""

  printf "  ${B}LiteLLM providers${R}\n"
  printf "  %-42s %s\n" "  relay provider add <name>"  "add a LiteLLM-compatible provider (alias: prov)"
  printf "  %-42s %s\n" "    --base-url <url>"         "required: http(s):// base URL of the gateway"
  printf "  %-42s %s\n" "    --token <token>"          "required: auth token/API key for the gateway"
  printf "  %-42s %s\n" "    --model <model>"          "optional: pin ANTHROPIC_MODEL to this alias"
  printf "  %-42s %s\n" "    --subagent-model <model>" "optional: pin CLAUDE_CODE_SUBAGENT_MODEL"
  printf "  %-42s %s\n" "                              " "(overrides every subagent's own model: frontmatter)"
  printf "  %-42s %s\n" "    --no-discover-models"     "opt out: gateway model discovery is on by default"
  printf "  %-42s %s\n" "    --codex"                  "target OpenAI's Codex CLI instead of Claude Code for this provider"
  printf "  %-42s %s\n" "                              " "(requires --model; --discover-models / --subagent-model don't apply)"
  printf "  %-42s %s\n" "  relay provider list"         "list configured providers + their settings"
  printf "  %-42s %s\n" "  relay provider remove <name>" "delete a provider (prompts for confirmation)"
  printf "  %-42s %s\n" "  relay provider codex-models <name>" "show/set a rotation list of models for --codex (no arg = show)"
  printf "  %-42s %s\n" "                              " "with no pinned --model, each --codex run rotates to the next one"
  echo ""

  printf "  ${B}Local proxies (manual)${R}\n"
  printf "  %-42s %s\n" "  relay proxy init"            "scaffold a local LiteLLM config template (alias: px)"
  printf "  %-42s %s\n" "  relay proxy start <name>"    "start litellm or bridge locally (never auto-started)"
  printf "  %-42s %s\n" "  relay proxy stop <name>"     "stop a running local proxy process"
  printf "  %-42s %s\n" "  relay proxy status [name]"   "check whether litellm/bridge are running"
  printf "  %-42s %s\n" "  relay proxy log <name>"      "tail a proxy's log file"
  printf "  %-42s %s\n" "  relay proxy bridge set-command '<cmd>'" "register the bridge process's launch command"
  printf "  %-42s %s\n" "                              " "(bridge is user-supplied — relay does not implement token bridging itself)"
  echo ""

  printf "  ${B}Autoswitch daemon${R}\n"
  printf "  %-42s %s\n" "  relay autoswitch config"     "interactive setup: order, thresholds, poll interval (alias: as)"
  printf "  %-42s %s\n" "  relay autoswitch start"      "install + start the background launchd/systemd daemon"
  printf "  %-42s %s\n" "  relay autoswitch stop"       "stop and uninstall the background daemon"
  printf "  %-42s %s\n" "  relay autoswitch status"     "daemon running state + per-account thresholds"
  printf "  %-42s %s\n" "  relay autoswitch log"        "tail the daemon's log file"
  printf "  %-42s %s\n" "  relay autoswitch"             "no subcommand: config if unset, else status"
  echo ""

  printf "  ${B}Locking (autoswitch)${R}\n"
  printf "  %-42s %s\n" "  relay lock <name>"        "exclude an account from autoswitch cycling when over limit"
  printf "  %-42s %s\n" "  relay unlock <name>"      "remove a lock"
  printf "  %-42s %s\n" "  relay lock"               "no argument: show all locked accounts"
  echo ""

  printf "  ${B}Warmup${R}\n"
  printf "  %-42s %s\n" "  relay warmup add <acct> <HH:MM>"    "schedule a daily pre-warm ping (24h local time)"
  printf "  %-42s %s\n" "  relay warmup remove <acct> [HH:MM]" "remove one scheduled time, or all for <acct> if omitted (alias: rm)"
  printf "  %-42s %s\n" "  relay warmup list"                  "show scheduled warmups + last-run result (alias: ls)"
  printf "  %-42s %s\n" "  relay warmup test <acct>"           "fire a warmup ping for <acct> right now, synchronously"
  printf "  %-42s %s\n" "  relay warmup pause"                 "suspend all warmups without deleting entries"
  printf "  %-42s %s\n" "  relay warmup resume"                "re-enable previously paused warmups"
  printf "  %-42s %s\n" "  relay warmup"                       "no subcommand: same as 'relay warmup list'"
  printf "  %-42s %s\n" "    requires the autoswitch daemon running (relay autoswitch start) to actually fire"
  echo ""

  printf "  ${B}Maintenance${R}\n"
  printf "  %-42s %s\n" "  relay version"    "show current version (alias: --version, -V)"
  printf "  %-42s %s\n" "  relay update"     "update relay to latest version"
  printf "  %-42s %s\n" "  relay install"    "(re)install shell integration / launcher"
  printf "  %-42s %s\n" "  relay uninstall"  "remove relay and all account data"
  printf "  %-42s %s\n" "  relay help"       "show this help (alias: --help, -h)"
  echo ""

  printf "  ${D}switches the OAuth credential (macOS Keychain / Linux ~/.claude/.credentials.json); sessions are shared${R}\n"
  printf "  ${D}after switching: claude -c to resume, claude --resume <id> for a specific session${R}\n\n"
  _check_update_bg
  _show_update_notice
}
