#!/usr/bin/env node
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const root = path.resolve(__dirname, '..');
const banner = '# Generated by scripts/build.cjs. Edit src/shell/ and src/python/, then run npm run build.\n';
const marker = /\{\{python:([a-z][a-z0-9_]*\.py)\}\}/g;

function assemble(projectRoot = root) {
  const version = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8')).version;
  if (typeof version !== 'string' || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error('package.json must contain a valid release version');
  }
  const manifest = JSON.parse(fs.readFileSync(path.join(projectRoot, 'src/manifest.json'), 'utf8'));
  if (!Array.isArray(manifest.shell) || manifest.shell.length === 0) {
    throw new Error('manifest.shell must be a nonempty ordered list');
  }
  const seen = new Set();
  const usedPython = new Set();
  const blankLineAfter = manifest.blankLineAfter || [];
  if (!Array.isArray(blankLineAfter) || new Set(blankLineAfter).size !== blankLineAfter.length ||
      blankLineAfter.some(name => !manifest.shell.includes(name))) {
    throw new Error('blankLineAfter must name distinct listed shell modules');
  }
  const parts = manifest.shell.map(name => {
    if (!/^[a-z][a-z0-9_-]*\.sh$/.test(name) || seen.has(name)) {
      throw new Error(`Invalid or duplicate shell module: ${name}`);
    }
    seen.add(name);
    // Boundary whitespace belongs to the manifest, not an editor's EOF policy.
    const source = fs.readFileSync(path.join(projectRoot, 'src/shell', name), 'utf8')
      .replace(/^\n+|\n+$/g, '') + '\n' + (blankLineAfter.includes(name) ? '\n' : '');
    return source.replace(marker, (_, pythonName) => {
      usedPython.add(pythonName);
      const python = fs.readFileSync(path.join(projectRoot, 'src/python', pythonName), 'utf8');
      if (!python.endsWith('\n') || python.includes('\r')) {
        throw new Error(`Python source must use LF and end in a newline: ${pythonName}`);
      }
      // The template owns the surrounding quotes/newlines. Do not shell-escape,
      // indent, trim whitespace, or evaluate the original Python program here.
      return python.slice(0, -1);
    });
  });
  for (const [directory, extension, used] of [
    ['shell', '.sh', seen], ['python', '.py', usedPython],
  ]) {
    for (const name of fs.readdirSync(path.join(projectRoot, 'src', directory))) {
      if (name.endsWith(extension) && !used.has(name)) {
        throw new Error(`Unreferenced ${directory} source: ${name}`);
      }
    }
  }
  const body = parts.join('');
  if (body.includes('{{python:')) throw new Error('Unexpanded Python marker');
  if (body.includes('\r')) throw new Error('Shell sources must use LF');
  if (!body.startsWith('#!/usr/bin/env bash\n') || !body.endsWith('\n')) {
    throw new Error('Assembled script must have its Bash shebang and final newline');
  }
  if ((body.match(/^#!\/usr\/bin\/env bash$/gm) || []).length !== 1) {
    throw new Error('Duplicate Bash entrypoint');
  }
  return body.replace('#!/usr/bin/env bash\n', '#!/usr/bin/env bash\n' + banner + `RELAY_BUILD_VERSION='${version}'\n`);
}

function main(args) {
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) {
    throw new Error('Usage: node scripts/build.cjs [--check]');
  }
  const output = assemble();
  const target = path.join(root, 'relay');
  if (args[0] === '--check') {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'relay-build-check-'));
    try {
      const candidate = path.join(temporary, 'relay');
      fs.writeFileSync(candidate, output);
      if (!fs.readFileSync(candidate).equals(fs.readFileSync(target))) {
        throw new Error('relay is out of date; run npm run build and commit the generated artifact');
      }
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
    console.log('Generated relay is up to date');
  } else {
    const temporary = target + '.build-tmp';
    try {
      fs.writeFileSync(temporary, output, { mode: 0o755, flag: 'wx' });
      fs.renameSync(temporary, target);
    } catch (error) {
      // Do not remove a temporary file owned by another concurrent build.
      if (error.code !== 'EEXIST') fs.rmSync(temporary, { force: true });
      throw error;
    }
    console.log('Built relay');
  }
}

if (require.main === module) {
  try { main(process.argv.slice(2)); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
module.exports = { assemble, banner };
